# Generated by Django 3.1.2 on 2020-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(blank=True, max_length=255, null=True)),
                ('movieyear', models.TextField(blank=True, default=2020, null=True)),
                ('movieid', models.CharField(blank=True, max_length=55, null=True, unique=True)),
                ('moviequality', models.CharField(blank=True, default=720, max_length=55)),
                ('moviecategory', models.CharField(blank=True, max_length=55)),
                ('movietrailer', models.CharField(blank=True, max_length=500)),
                ('movieratings', models.FloatField(blank=True, null=True)),
                ('moviegenre', models.CharField(blank=True, max_length=255, null=True)),
                ('moviedate', models.DateField(blank=True, null=True)),
                ('movielang', models.CharField(blank=True, max_length=55, null=True)),
                ('moviehomepage', models.CharField(blank=True, max_length=255, null=True)),
                ('movieruntime', models.CharField(blank=True, max_length=33, null=True)),
                ('moviekeywords', models.TextField(blank=True, null=True)),
                ('moviestory', models.TextField(blank=True, null=True)),
                ('moviewatchlink', models.TextField(blank=True, null=True)),
                ('moviesubtitle', models.TextField(blank=True, null=True)),
                ('movieactors', models.TextField(blank=True, null=True)),
                ('moviesize', models.CharField(blank=True, max_length=55, null=True)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('uploadeduser', models.CharField(blank=True, max_length=55, null=True)),
                ('uploadtime', models.DateTimeField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('published', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-uploadtime'],
            },
        ),
    ]
