# Generated by Django 3.1.2 on 2020-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviesgenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
            ],
        ),
    ]
