# Generated by Django 3.0.8 on 2020-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('fullname', models.CharField(db_column='fullName', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(blank=True, db_column='MobileNumber', max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('aboutme', models.TextField(blank=True, db_column='aboutMe', null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=11)),
                ('role', models.IntegerField()),
                ('profile', models.CharField(max_length=155)),
                ('theme', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allmovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(blank=True, db_column='MovieTitle', max_length=255, null=True)),
                ('movieyear', models.TextField(blank=True, db_column='MovieYear', null=True)),
                ('movieid', models.CharField(blank=True, db_column='MovieID', max_length=55, null=True, unique=True)),
                ('moviequality', models.CharField(db_column='MovieQuality', max_length=55)),
                ('moviecategory', models.CharField(db_column='MovieCategory', max_length=55)),
                ('movietrailer', models.CharField(db_column='MovieTrailer', max_length=500)),
                ('movieratings', models.FloatField(blank=True, db_column='MovieRatings', null=True)),
                ('moviegenre', models.CharField(blank=True, db_column='MovieGenre', max_length=255, null=True)),
                ('moviedate', models.DateField(blank=True, db_column='MovieDate', null=True)),
                ('movielang', models.CharField(blank=True, db_column='Movielang', max_length=55, null=True)),
                ('moviehomepage', models.CharField(blank=True, db_column='Moviehomepage', max_length=255, null=True)),
                ('movieruntime', models.CharField(blank=True, db_column='MovieRuntime', max_length=33, null=True)),
                ('moviekeywords', models.TextField(blank=True, db_column='MovieKeywords', null=True)),
                ('moviestory', models.TextField(blank=True, db_column='MovieStory', null=True)),
                ('moviewatchlink', models.TextField(blank=True, db_column='MovieWatchLink', null=True)),
                ('moviesubtitle', models.TextField(blank=True, db_column='MovieSubtitle', null=True)),
                ('movieactors', models.TextField(blank=True, db_column='MovieActors', null=True)),
                ('moviesize', models.CharField(blank=True, db_column='MovieSize', max_length=55, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadeduser', models.CharField(blank=True, db_column='uploadedUser', max_length=55, null=True)),
                ('uploadtime', models.DateTimeField(db_column='uploadTime')),
                ('views', models.IntegerField(blank=True, null=True)),
                ('published', models.IntegerField()),
            ],
            options={
                'db_table': 'allmovies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiskSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_column='Path', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
            ],
            options={
                'db_table': 'disk_setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=555)),
                ('cover_pic', models.CharField(max_length=555)),
                ('trailer', models.CharField(max_length=222)),
                ('download', models.CharField(max_length=111)),
                ('details', models.TextField()),
                ('con_cat', models.CharField(max_length=55)),
                ('hit', models.IntegerField()),
                ('filesize', models.CharField(max_length=55)),
                ('published', models.IntegerField()),
                ('uploader', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logininfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('ipaddress', models.CharField(max_length=155)),
                ('serverip', models.CharField(max_length=155)),
                ('login', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'logininfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=33)),
                ('visible', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moviesgenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
            ],
            options={
                'db_table': 'moviesgenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=33)),
                ('noti', models.CharField(max_length=255)),
                ('ndatetime', models.DateTimeField(db_column='nDatetime')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(db_column='websiteName', max_length=255)),
                ('websiteurl', models.CharField(db_column='websiteUrl', max_length=255)),
                ('webid', models.IntegerField(db_column='WebID')),
                ('websitelogo', models.CharField(db_column='websiteLogo', max_length=255)),
                ('theme', models.CharField(max_length=100)),
                ('layout', models.CharField(max_length=55)),
                ('skin', models.CharField(max_length=11)),
                ('slider', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exordid', models.CharField(max_length=155)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('reply_text', models.CharField(max_length=255)),
                ('user_ip', models.CharField(max_length=115)),
                ('cate', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'shoutbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='Date')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('downlink', models.TextField(db_column='downLink')),
                ('cata', models.IntegerField()),
                ('filesize', models.CharField(max_length=155)),
                ('upby', models.CharField(max_length=155)),
                ('publish', models.IntegerField()),
                ('views', models.IntegerField()),
                ('picu', models.IntegerField(db_column='picU')),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Todaypageviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('referrer', models.CharField(max_length=255)),
                ('hit_date', models.DateField()),
            ],
            options={
                'db_table': 'todaypageviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tvepisodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvid', models.IntegerField(db_column='TVID')),
                ('episode_number', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('epiid', models.IntegerField(db_column='EPIID', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('still_path', models.CharField(max_length=555)),
                ('overview', models.TextField()),
                ('quality', models.CharField(max_length=55)),
                ('watchlink', models.TextField()),
                ('air_date', models.DateField()),
                ('up_time', models.DateTimeField()),
                ('hit', models.IntegerField()),
                ('upby', models.CharField(max_length=255)),
                ('published', models.IntegerField()),
            ],
            options={
                'db_table': 'tvepisodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tvgenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'tvgenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tvseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvtitle', models.CharField(db_column='TVtitle', max_length=255)),
                ('tvid', models.IntegerField(db_column='TVID', unique=True)),
                ('tvcategory', models.CharField(db_column='TVcategory', max_length=55)),
                ('tvtrailer', models.CharField(db_column='TVtrailer', max_length=255)),
                ('tvratings', models.FloatField(db_column='TVRatings')),
                ('tvgenre', models.CharField(db_column='TVgenre', max_length=255)),
                ('tvrelease', models.IntegerField(db_column='TVrelease')),
                ('tvlang', models.CharField(db_column='TVlang', max_length=155)),
                ('tvhomepage', models.CharField(db_column='TVhomepage', max_length=155)),
                ('tvruntime', models.CharField(db_column='TVruntime', max_length=55)),
                ('tvkeywords', models.TextField(db_column='TVkeywords')),
                ('tvstory', models.TextField(db_column='TVstory')),
                ('tvactors', models.CharField(db_column='TVactors', max_length=255)),
                ('tvposter', models.CharField(db_column='TVposter', max_length=255)),
                ('uploadeduser', models.CharField(db_column='uploadedUser', max_length=55)),
                ('uploadtime', models.DateTimeField(db_column='uploadTime')),
                ('views', models.IntegerField()),
                ('published', models.IntegerField()),
            ],
            options={
                'db_table': 'tvseries',
                'managed': False,
            },
        ),
    ]
